# Generated by Django 4.2.2 on 2023-06-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_remove_inventoryproduct_inventory_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='inventory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Management.inventory', verbose_name='انبار'),
        ),
    ]
